apiVersion: v1
kind: Secret
metadata:
  name: example-mysql-password
type: Opaque
data:
  password: UGFzc3cwcmQh # Passw0rd!
---
apiVersion: database.ihypo.net/v1
kind: MySQL
metadata:
  name: example-mysql
spec:
  type: Cluster
  members: 3
  auth:
    rootPasswordSecret:
      name: example-mysql-password